name: api-lb
defaultService: global/backendServices/api-lb-service
hostRules:
  - hosts:
      - '*'
    pathMatcher: matcher-1
pathMatchers:
  - name: matcher-1
    defaultService: global/backendServices/api-lb-service
    routeRules:
      - priority: 1
        routeAction:
          weightedBackendServices:
            - backendService: global/backendServices/api-lb-read-service-0
              weight: 33
            - backendService: global/backendServices/api-lb-read-service-1
              weight: 33
            - backendService: global/backendServices/api-lb-read-service-2
              weight: 33
        matchRules:
          - pathTemplateMatch: /v0/bets
          - pathTemplateMatch: /v0/comments
          - pathTemplateMatch: /get-best-comments
          - pathTemplateMatch: /get-contract
          - pathTemplateMatch: /v0/market/*
          - pathTemplateMatch: /v0/market/*/groups
          - pathTemplateMatch: /v0/market/*/positions
          - pathTemplateMatch: /v0/markets
          - pathTemplateMatch: /v0/search-markets
          - pathTemplateMatch: /search-markets-full
          - pathTemplateMatch: /get-related-markets
          - pathTemplateMatch: /get-related-markets-by-group
          - pathTemplateMatch: /v0/groups
          - pathTemplateMatch: /search-groups
          - pathTemplateMatch: /search-my-groups
          - pathTemplateMatch: /v0/get-followed-groups
          - pathTemplateMatch: /get-groups-with-top-contracts
          - pathTemplateMatch: /v0/me
          - pathTemplateMatch: /v0/me/private
          - pathTemplateMatch: /v0/user/by-id/*
          - pathTemplateMatch: /v0/user/by-id/*/lite
          - pathTemplateMatch: /v0/user/*
          - pathTemplateMatch: /v0/user/*/lite
          - pathTemplateMatch: /v0/user/*/bets
          - pathTemplateMatch: /get-balance-changes
          - pathTemplateMatch: /get-user-limit-orders-with-contracts
          - pathTemplateMatch: /get-user-portfolio
          - pathTemplateMatch: /get-user-portfolio-history
          - pathTemplateMatch: /v0/users
          - pathTemplateMatch: /search-users
          - pathTemplateMatch: /v0/managrams
          - pathTemplateMatch: /v0/txns
          - pathTemplateMatch: /headlines
          - pathTemplateMatch: /politics-headlines
          - pathTemplateMatch: /get-dashboard-from-slug
          - pathTemplateMatch: /get-feed
          - pathTemplateMatch: /v0/leagues
          - pathTemplateMatch: /v0/get-mod-reports
          - pathTemplateMatch: /get-notifications
          - pathTemplateMatch: /markets-by-ids
          - pathTemplateMatch: /v0/generate-ai-market-suggestions
          - pathTemplateMatch: /v0/generate-ai-market-suggestions-2
          - pathTemplateMatch: /get-daily-changed-metrics-and-contracts
          - pathTemplateMatch: /v0/get-monthly-bets-2024
          - pathTemplateMatch: /v0/get-max-min-profit-2024
          - pathTemplateMatch: /get-next-loan-amount
          - pathTemplateMatch: /0/generate-ai-answers
          - pathTemplateMatch: /0/generate-ai-description
# redeploy this by running:
# gcloud compute url-maps import api-lb --source=url-map-config.yaml --project mantic-markets  --global
# (or for dev, --project dev-mantic-markets)
