[programs.localnet]
dpm = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jahooma/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
