name: Reformat main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]

env:
  FORCE_COLOR: 3
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  prettify:
    name: Auto-prettify
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FORMATTER_ACCESS_TOKEN }}
      - name: Restore cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
      - name: Install missing dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Run Prettier on web client
        working-directory: web
        run: yarn format
      - name: Commit any Prettier changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-prettification
          branch: ${{ github.head_ref }}
